name: tests
on: [push]

jobs:
  test:
    name: Node.js ${{ matrix.node_version }} & Experimental ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12]
        experimental: [true, false]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Test
      run: |
        npm install
        npx ava
      env:
        FORCE_COLOR: true
        EXPERIMENAL: ${{ matrix.experimental }}
